[target.'cfg(target_os = "none")']
runner = "cargo run --package boot --"

[alias]
kbuild = "build --target x86_64-kern_test.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-kern_test.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-kern_test.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --target x86_64-kern_test.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"

